default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: ror_budget_maker_development
  host: localhost
  username: dilsh
  password: dilsher

test:
  <<: *default
  database: ror_budget_maker_test
  host: localhost
  username: dilsh
  password: dilsher

production:
  <<: *default
  database: ror_budget_maker_production
  username: ror_budget_maker
  password: <%= ENV["ROR_BUDGET_MAKER_DATABASE_PASSWORD"] %>
